### ISSUE TITLE
Server platform

### ISSUE THREAD

**Issue by adkulas** [ece651-winter2019/ece651-group-project#9]
Determine where to host and run the application and services

**Comment by gaberch** [comment]
Docker image has been created. Will try to upload to Azure either tonight or tomorrow morning.

**Comment by gaberch** [comment]
Wed. Feb 6, 2019 Update:

- Tried creating pipeline with docker image but Azure documentation seems to point to the fact that it either needs to build an image for an already built app in the pipeline or potentially link to an image registry (Azure's image registry or DockerHub)
      - Azure's image registry is an extra service that we have to each sign up for
      - Decided to go with DockerHub for simplicity

- Created DockerHub account and pushed docker image to the Hub
     - Was having issues when pushing to an organization account repository (created organization so that we can have the whole team there)
     - Had success pushing to DockerHub personal account repository
     - Location of image in repo is at the following link: 
https://cloud.docker.com/repository/docker/gaberch/test
     - You will need to create a personal account to access (it's free)

- Next Steps: 
      - Figure out how to link DockerHub personal account repo to Azure DevOps pipeline and work with that image instead of having Azure building an image

**Comment by gaberch** [comment]
Feb 7, 2019 - Feb 12, 2019 Update:

- DockerHub personal account repo has been linked to Azure. Azure Devops does the CI/CD work in the build process and is then capable of either deploying the build via an app or an image to the appropriate Azure service

- Deployed a test app using a custom image using Web App for Containers by Azure. Custom docker image was provided by Azure. Image is built using a docker file. Will try to do this with back end test pyramid app. Link is gabesapp.azurewebsites.net

Current Issues:

- Dockerfile build fails right at end of back end set of instructions when you initialize database and initialize the server to a specific port. Need to better understand what the pyramid example tutorial is doing when running the the initialization commands. 

Nest Steps:
-   Better understand pyramid test example and what it's doing when initializing database and initialize the server to a specific port. Maybe the server initialization command can't be carried out the same way as when simply running locally.

**Comment by gaberch** [comment]
Feb 13, 2019 - Feb 14, 2019 Update:

- Was unable to successfully build a docker image using Adam's pyramid app example. Moved on to build another pyramid example in docker. Docker image example was created successfully. Docker container able to run locally.

- After looking more into cloud services are more recommended for quick deployment and development  at a very low cost or free, I have come across Heroku which has significantly more free services than Azure. I switched over to using Heroku to attempt to deploy pyramid container.

- Pyramid container exposed port is unable to be picked up by Heroku. Found out that you can't expose a specific port and have Heroku pick it up. You must use a port variable which Heroku will assign when deploying. Tried a few iterations of this made when building multiple images of the pyramid app. Final Result: Unable to successfully connect Heroku port to container port.

- Due to this result, I went forward with simply deploying the pyramid app itself to Heroku by creating an example pyramid app and pushing it to GitHub. The GitHub repo is then connected to Heroku. An app is then created in Heroku and the code is deployed. The deployment was successful and the app is currently live here: http://pyramid-backend.herokuapp.com/

Next Steps: 

- Deploy Java Mobile App to Heroku

**Comment by gaberch** [comment]
Feb 15, 2019 Update:

- Initial run of commands instructions to build MobileApp failed. Returned error "./gradlew: command not found"

- Solution to problem was to set ./gradlew as an executable by running the following command:
chmod +x ./gradlew

- Was successfully able to build the app locally

- When deploying to Heroku, the initial build failed. In order to localize the issues, a sample gradle deployment tutorial was carried out using Heroku's instructions. Successful deployment can be found at: https://test-graddle-deployment.herokuapp.com/

- Currently unable to successfully deploy ECE 651 MobileApp to Heroku. When checking the differences between sample tutorial and our version of the gradle build script I found that we are declaring our app dependencies within a module as opposed to up front. We also do not declare a Procfile. Our folder has a few extra files such as local.properties, gradle.properties and torontotong_MobileApplication.iml. I suspect that creating the Procfile may be the issue. 

- To be continued...

Next Steps:

- Figure out Graddle App deployment issue to Heroku issue

**Comment by gaberch** [comment]
Feb 16, 2019 Update:

- I've researched more into deploying the Android app to Heroku and have come to the conclusion that it doesn't make sense to do so. When looking into this, I couldn't find any documentation as to how to do this on Heroku which made me wonder why (I can't be the first person to think about deploying an Android app to Heroku). My conclusion to this is that it doesn't make sense to host it on the cloud since the app would be communicating with the backend via APIs. The backend is hosted on Heroku and can therefore communicate with the app at any time but I don't see the point of hosting the app on the cloud and based on my research, android apps don't seem to be typically hosted on the cloud. This makes sense since you would need to basically install an emulator on the cloud and then install the app on the emulator. This would only make sense with a virtual machine. However, we can still deploy the app to Google App Store.

Next Steps:

- Discuss with team if this logic is sound and that there's no need to deploy Android App to Heroku.

**Comment by gaberch** [comment]
Conclusion: 

- Mobile app will be available for download from a link on the web app that will be hosted on Heroku.
